import pandas as pd
import numpy as np
from hmmlearn import hmm
from pathlib import Path
import time
import sys
import threading
import random


    # This is more or less the same as the previous script but it does not slice the data set into two partitions.
    # THis script evaluates the whole timeline to show the difference between outputs.

def the_hidden_one(input_parquet, output_csv):

    print(f"Loading data from {input_parquet.name}... ")
    enron_df = pd.read_parquet(input_parquet)

    print("Arranging emails chronologically by sender...")

    # Parsing Enron timestamps
    enron_df['clean_timestamp'] = enron_df['timestamp'].str.replace(r'\s*\([A-Z]+\)\s*$', '', regex = True)
    enron_df['parsed_date'] = pd.to_datetime(enron_df['clean_timestamp'], errors = 'coerce', utc = True)

    enron_df = enron_df.dropna(subset = ['parsed_date'])
    enron_df = enron_df.sort_values(by = ['sender', 'parsed_date'])

    # To filter out the noise: A chain must have 10+ emails to be considered a full sequence
    email_counts = enron_df['sender'].value_counts()
    valid_senders = email_counts[email_counts >= 10].index
    enron_df = enron_df[enron_df['sender'].isin(valid_senders)].copy()

    print(f"Filtered down to  {len(valid_senders)} senders.")
    print(f"Preparing data for Markov Model...")

    # This bit just ensures the program does not crash
    enron_df = enron_df.dropna(subset = ['anomaly_score'])

    # Reshaping anomaly scores
    global_emission_vector = enron_df['markov_state'].to_numpy().reshape(-1, 1)

    # Mapping boundaries
    timeline_boundary = enron_df.groupby('sender', sort = False).size().tolist()

    print("Initialising Model...")

    # MODEL CONFIGURATION
    hidden_markov_model = hmm.CategoricalHMM(
        n_components = 4,
        n_iter = 100,
        random_state = 42
    )

    training_complete = False

    def dice_roll():
           nonlocal training_complete
           while not training_complete:
               roll = f"{random.randint(1, 20):2d}"
               sys.stdout.write(f'\r>>> ROLLING FOR INSIGHT... Hold on to your butts! d{roll}') 
               sys.stdout.flush()
               time.sleep(0.1)
   
    dice_thread = threading.Thread(target = dice_roll)
   
    start_time = time.time()
    dice_thread.start()
   
    try:
        hidden_markov_model.fit(global_emission_vector, lengths = timeline_boundary)
    finally:
        training_complete = True
        dice_thread.join()
   
        sys.stdout.write('\r' + ' ' * 60 + '\r')
        sys.stdout.flush()

    end_time = time.time()
    total_seconds = end_time - start_time

    minutes, seconds = divmod(total_seconds, 60)

    print(f"Completed in {int(minutes)}m {seconds:.2f}s")

    print("Decoding hidden states...")
    enron_df['predicted_hidden_state'] = hidden_markov_model.predict(global_emission_vector, lengths = timeline_boundary)

    # This code makes sure the states are properly and logically aligned.
    # Without this, the anomaly scores would be inverted.
    state_mean = enron_df.groupby('predicted_hidden_state')['anomaly_score'].mean()
    severity = state_mean.sort_values(ascending = False).index.tolist()
    severity_alignment = {old_state: new_state for new_state, old_state in enumerate(severity)}
    enron_df['threat_profile'] = enron_df['predicted_hidden_state'].map(severity_alignment)
    enron_df = enron_df.drop(columns = ['predicted_hidden_state'])

    # The Matrix Extraction
    print("\n --- HIDDEN TRANSITION MATRIX ---")
    print("Rows = Current Hidden State | Columns = Next Hidden State")

    raw_escalation_matrix = hidden_markov_model.transmat_
    aligned_escalation_matrix = raw_escalation_matrix[np.ix_(severity, severity)]

    # This extracts the matrix generated by the Baum-Welch algorithm
    state_flow_grid = pd.DataFrame(aligned_escalation_matrix).round(4)
    print(state_flow_grid)

    state_label = [f"State {i}" for i in range(aligned_escalation_matrix.shape[0])]
    state_flow_grid.index = state_label
    state_flow_grid.columns = state_label

    global_csv_path = output_csv.parent / "transition_matrix_global.csv"
    state_flow_grid.to_csv(global_csv_path)
    print(f"Global Matrix saved to {global_csv_path.name}")

    # Saving the dataset for analysis and evaluation
    enron_df.to_csv(output_csv, index = False)
    print(f"\n Timeline with predicted states saved to {output_csv.name}")

if __name__ == "__main__":
    BASE_DIR = Path(__file__).resolve().parent.parent

    input_file = BASE_DIR / "deliverables" / "enron_multiclass_states.parquet"
    output_file = BASE_DIR / "deliverables" / "global_hidden_states.csv"

    the_hidden_one(input_file, output_file)

