import pandas as pd
from pathlib import Path

def multiclass_states(input_parquet, output_parquet):

    print(f"Ingesting features from {input_parquet.name}...")
    df = pd.read_parquet(input_parquet)

    print("Sorting continuous scores into probability distributions...")

    # This script is what will allow the Markov Model to work as intended.
    # The easiest way to explain the Markov Model itself is that it works of a series of theoretical rooms.
    # If a person had the choice of going into Room 1 or Room 2 the Markov Model needs to predict which room they will go into and where from.
    # The problem is that it cannot do calculations for this as the scores generated by the Isolation Forest are infinite decimals and the chances of a decimal score being the same as another is essentially zero.
    # To solve this problem this script will discretise the data with the Quantile Cut function from pandas.
    
    # pd.qcut will divide the anomaly scores into buckets of probability.
    # Lower scores = more anomalous. The states are defined as follows:
    # 0.00 to 0.01 (Bottom 1%) = State 3 (Critical)
    # 0.01 to 0.05 (4%)        = State 2 (Suspicious)
    # 0.05 to 0.20 (15%)       = State 1 (Irregular)
    # 0.20 to 1.00 (Top 80%)   = State 0 (Normal)

    quantiles = [0, 0.01, 0.05, 0.20, 1.0]

    # Labels match the quantiles from the most to least anomalous
    state_labels = [3, 2, 1, 0]

    # Set up the quantisation needed for the Markov Model
    df['markov_state'] = pd.qcut(df['anomaly_score'], q = quantiles, labels = state_labels, duplicates = 'drop')

    # Calculate and show the exact percentage distribution to check the threshold logic
    distribution = df['markov_state'].value_counts(normalize = True).sort_index(ascending = False) * 100

    print("\n Markov State Probability Distribution")
    for state, percentage in distribution.items():
        if state == 3: print(f"State 3 (Critical) : {percentage:.2f}%")
        elif state == 2: print(f"State 2 (Suspicious): {percentage:.2f}%")
        elif state == 1: print(f"State 1 (Irregular): {percentage:.2f}%")
        elif state == 0: print(f"State 0 (Normal): {percentage:.2f}%")

    df.to_parquet(output_parquet)
    print(f"\nMulticlass labelling complete. Saved to {output_parquet.name}")

if __name__ == "__main__":
    BASE_DIR = Path(__file__).resolve().parent.parent
    
    input_file = BASE_DIR / "deliverables" / "enron_scored_features.parquet"
    output_file = BASE_DIR / "deliverables" / "enron_multiclass_states.parquet"

    multiclass_states(input_file, output_file)

